FROM debian:jessie

MAINTAINER dst103

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
            	apache2 \
      		php5 \
		php5-mcrypt \
		php5-mysqlnd \
		mysql-client
RUN a2enmod \
            	php5 \
        	rewrite
RUN sed -i "s/memory_limit = 128M/memory_limit = 512M/" /etc/php5/apache2/php.ini && \
sed -i "s/post_max_size = 8M/post_max_size = 20M/" /etc/php5/apache2/php.ini && \
sed -i "s/upload_max_filesize = 2M/upload_max_filesize = 20M/" /etc/php5/apache2/php.ini

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /mnt/host/logs
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

EXPOSE 80

ADD apache-config.conf /etc/apache2/sites-enabled/000-default.conf

CMD /usr/sbin/apache2ctl -D FOREGROUND
